### ISSUE TITLE
🚀 Feature: Rule options

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [octoguide/bot#20]
### Feature Request Checklist

- [x] I have pulled the latest `main` branch of the repository.
- [x] I have [searched for related issues](https://github.com/JoshuaKGoldberg/octoguide/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

Lint rules often need to be configured. For example, in `pr-linked-issue`, requiring a configurable list of labels on the linked issue. OctoGuide will need to allow:

1. Defining a schema of options on a rule
2. Allowing repos to define values for options as `with:` options

Both the action and CLI will need to read from that file, including fetching it.

### Additional Info

I'm envisioning the end user config experience will be like:

```yml
jobs:
  octoguide:
    if: ${{ !endsWith(github.actor, '[bot]') }}
    runs-on: ubuntu-latest
    steps:
      - uses: JoshuaKGoldberg/octoguide@v0.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          rules:
               my-rule:
                    option: true
```

Rules would then have an `options` field in their `about` that's set to an object of Zod schemas:

```ts
export const myRule = {
	about: {
		config: "strict",
		// ...
		options: {
			"some-option": z.string().optional()
		},
	},
	// ...
} satisfies Rule;
```

~Blocked on #19 - implementing an action in the first place.~ ✅ 

🗺
